### ISSUE TITLE
Hoster doesn't support mod_perl

### ISSUE THREAD

**Issue by emmesscee** [bayoteers/Dashboard#3]
Hi, 
I tried to add this extension but after ./checksetup.pl got:
Checking for            mod_perl (v1.999022) not found 
Checking for     Apache-SizeLimit (v0.96)     not found

I checked my hosters docs and found:
/usr/bin/perl
mod_perl is currently not supported at DreamHost. You must use FastCGI instead. 

Any suggestions of a workaround?
Thanks!

**Comment by keto** [comment]
mod_perl and Apache-SizeLimit are optional Bugzilla requirements and have nothing to do with the Dashboard extension.

Bugzilla works also under mod_cgi http://bugzilla.readthedocs.org/en/latest/installing/apache.html#apache-with-mod-cgi
